### PR TITLE
[WIP] Fixes for eager execution

### PR DESCRIPTION
**Pull request by dfalbel**

### CODE REVIEW

**Comment by skeydan** [comment]
This is interesting! We discussed that a few months ago and decided not to do it (meaning, adding those S3 methods) at that time. 
Now that some time has passed, I don't exactly recall the details, but I think "most stuff worked" after switching to `tf.keras` backend even without those methods - although class hierarchies did look funny because sometimes the more specific classes showed up with a prefix of `tensorflow.python.keras` but the more general ones had `keras.xxx` ...

Would you mind quickly explaining why we are now required to do this while we got along before?

**Comment by skeydan** [comment]
Adding to the above, I think we also discussed this

```
# register class filter to alias classes to 'keras'
      reticulate::register_class_filter(function(classes) {
        sub(paste0("^", resolve_implementation_module()), "keras", classes)
})
```

in `packages.R` but decided to leave it as is in order not to break dependent packages...

**Comment by dfalbel** [comment]
The problem we are having in eager is directly related to the classes. In eager the Sequential Model gets the following classes:

``` r
reticulate::use_virtualenv("tf-1.13.1")
tensorflow::tfe_enable_eager_execution()

library(keras)

model <- keras_model_sequential()
class(model)
#> [1] "tensorflow.python.keras.engine.sequential.Sequential"      
#> [2] "tensorflow.python.keras.engine.training.Model"             
#> [3] "tensorflow.python.keras.engine.network.Network"            
#> [4] "tensorflow.python.keras.engine.base_layer.Layer"           
#> [5] "tensorflow.python.module.module.Module"                    
#> [6] "tensorflow.python.training.tracking.tracking.AutoTrackable"
#> [7] "tensorflow.python.training.tracking.base.Trackable"        
#> [8] "python.builtin.object"
```

In the graph mode we have: 

``` r
reticulate::use_virtualenv("tf-1.13.1")
#tensorflow::tfe_enable_eager_execution()

library(keras)

model <- keras_model_sequential()
class(model)
#> [1] "keras.engine.sequential.Sequential"                        
#> [2] "keras.engine.training.Model"                               
#> [3] "keras.engine.network.Network"                              
#> [4] "keras.engine.base_layer.Layer"                             
#> [5] "tensorflow.python.module.module.Module"                    
#> [6] "tensorflow.python.training.tracking.tracking.AutoTrackable"
#> [7] "tensorflow.python.training.tracking.base.Trackable"        
#> [8] "python.builtin.object"
```

I didn't see this class filters, now I wonder why it's not filtering correctly in eager...

**Comment by skeydan** [comment]
yeah, right! I think that the time (going through the `tfdatasets` tests - I thought that this was related to whether you load `tensorflow` (via `tfdatasets`) first or `keras`.
But actually `eager` makes all the difference!

```
library(tensorflow)
#tfe_enable_eager_execution()
library(keras)

model <- keras_model_sequential()
class(model)
```

**Comment by skeydan** [comment]
No, wait!! It _has_ to do with load order:

```
> library(keras)
> tensorflow::tfe_enable_eager_execution()
> model <- keras_model_sequential()
> class(model)
[1] "keras.engine.sequential.Sequential"                        
[2] "keras.engine.training.Model"                               
[3] "keras.engine.network.Network"                              
[4] "keras.engine.base_layer.Layer"                             
[5] "tensorflow.python.module.module.Module"                    
[6] "tensorflow.python.training.tracking.tracking.AutoTrackable"
[7] "tensorflow.python.training.tracking.base.Trackable"        
[8] "python.builtin.object"                                     
> 
```

**Comment by skeydan** [comment]
so on a very general level, this means the class filter only gets activated if `keras` is loaded first right?

**Comment by dfalbel** [comment]
Yes! It seems to be a bug in reticulate which is only using the first registered filter

**Comment by skeydan** [comment]
oh, that sounds great (for us ;-))!

**Comment by dfalbel** [comment]
Turns out it's keras that is not registering the filter

```
reticulate::use_virtualenv("tf-1.13.1")

tensorflow::tfe_enable_eager_execution()


library(keras)

model <- keras_model_sequential()
class(model)
#> [1] "tensorflow.python.keras.engine.sequential.Sequential"      
#> [2] "tensorflow.python.keras.engine.training.Model"             
#> [3] "tensorflow.python.keras.engine.network.Network"            
#> [4] "tensorflow.python.keras.engine.base_layer.Layer"           
#> [5] "tensorflow.python.module.module.Module"                    
#> [6] "tensorflow.python.training.tracking.tracking.AutoTrackable"
#> [7] "tensorflow.python.training.tracking.base.Trackable"        
#> [8] "python.builtin.object"
reticulate:::.globals$class_filters
#> [[1]]
#> function (classes) 
#> {
#>     if (any(c("tensorflow.python.ops.variables.Variable", "tensorflow.python.framework.ops.Tensor") %in% 
#>         classes)) {
#>         c("tensorflow.tensor", classes)
#>     }
#>     else {
#>         classes
#>     }
#> }
#> <bytecode: 0x7fe6b514d680>
#> <environment: 0x7fe6b5151bf8>
```

**Pull request closed without merging**
