### PR TITLE
update examples

### PR DESCRIPTION
**Pull request by henry090**
Hi, Could you review these 2 files, please?

### CODE REVIEW

**Comment by skeydan** [comment]
Looks great, thank you! Can you check if in `mmd-cvae.R`, you actually *need* to specify `float32` as a layer dtype? I mean: just for the layers, not the data, that is, just in expressions like 

```
self$dense <- layer_dense(units = 7 * 7 * 32, activation = "relu",dtype='float32')
```

(`float32` should actually be the default).

If that works, you could also check if the casts are still needed inside of `normal_loglik`.

Ideally, once you cast the input data to `float32`, everything else should not be needed any more - but we would need to verify.

**Comment by henry090** [comment]
Hi,
With this line:
```
self$dense <- layer_dense(units = 7 * 7 * 32, activation = "relu")
```
this one throws:
```
> generate_random_clothes(0)
WARNING:tensorflow:Layer dense_1 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because its dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.
```
And the loop at the end of the script throws:
```
Error: InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Mul]

```
Then I restored everything and changed only ```normal_loglik``` to ```float32``` and still get the following:
```
Error: InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Mul]
```
If I change input:
```
train_x <-
  train_images %>% `/`(255) %>% k_reshape(c(60000, 28, 28, 1)) %>% k_cast('float32')
test_x <-
  test_images %>% `/`(255) %>% k_reshape(c(10000, 28, 28, 1)) %>% k_cast('float32')

how_grid(0)
WARNING:tensorflow:Layer dense_1 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because its dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.
```
And loop at the end:
```
Error: InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Mul]
```
Finally, 
```

> library(keras)
> library(tensorflow)
> library(tfdatasets)
> library(dplyr)
> library(ggplot2)
> library(glue)
> fashion <- dataset_fashion_mnist()
> c(train_images, train_labels) %<-% fashion$train
> c(test_images, test_labels) %<-% fashion$test
> train_x <-
+   train_images %>% `/`(255) %>% k_reshape(c(60000, 28, 28, 1)) %>% k_cast('float32')
2020-04-20 12:08:13.755384: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-04-20 12:08:13.778099: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc59f2bdfd0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-20 12:08:13.778125: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> test_x <-
+   test_images %>% `/`(255) %>% k_reshape(c(10000, 28, 28, 1)) %>% k_cast('float32')
> class_names = c('T-shirt/top',
+                 'Trouser',
+                 'Pullover',
+                 'Dress',
+                 'Coat', 
+                 'Sandal',
+                 'Shirt',
+                 'Sneaker',
+                 'Bag',
+                 'Ankle boot')
> buffer_size <- 60000
> batch_size <- 100
> batches_per_epoch <- buffer_size / batch_size
> train_dataset <- tensor_slices_dataset(train_x) %>%
+   dataset_shuffle(buffer_size) %>%
+   dataset_batch(batch_size)
> test_dataset <- tensor_slices_dataset(test_x) %>%
+   dataset_batch(10000)
> latent_dim <- 2
> encoder_model <- function(name = NULL) {
+   keras_model_custom(name = name, function(self) {
+     self$conv1 <-
+       layer_conv_2d(
+         filters = 32,
+         kernel_size = 3,
+         strides = 2,
+         activation = "relu"
+       )
+     self$conv2 <-
+       layer_conv_2d(
+         filters = 64,
+         kernel_size = 3,
+         strides = 2,
+         activation = "relu"
+       )
+     self$flatten <- layer_flatten()
+     self$dense <- layer_dense(units = 2 * latent_dim)
+     
+     function (x, mask = NULL) {
+       x %>%
+         self$conv1() %>%
+         self$conv2() %>%
+         self$flatten() %>%
+         self$dense() %>%
+         tf$split(num_or_size_splits = 2L, axis = 1L) 
+     }
+   })
+ }
> decoder_model <- function(name = NULL) {
+   keras_model_custom(name = name, function(self) {
+     self$dense <- layer_dense(units = 7 * 7 * 32, activation = "relu")
+     self$reshape <- layer_reshape(target_shape = c(7, 7, 32))
+     self$deconv1 <-
+       layer_conv_2d_transpose(
+         filters = 64,
+         kernel_size = 3,
+         strides = 2,
+         padding = "same",
+         activation = "relu"
+       )
+     self$deconv2 <-
+       layer_conv_2d_transpose(
+         filters = 32,
+         kernel_size = 3,
+         strides = 2,
+         padding = "same",
+         activation = "relu"
+       )
+     self$deconv3 <-
+       layer_conv_2d_transpose(
+         filters = 1,
+         kernel_size = 3,
+         strides = 1,
+         padding = "same"
+       )
+     
+     function (x, mask = NULL) {
+       x %>%
+         self$dense() %>%
+         self$reshape() %>%
+         self$deconv1() %>%
+         self$deconv2() %>%
+         self$deconv3()
+     }
+   })
+ }
> reparameterize <- function(mean, logvar) {
+   eps <- k_random_normal(shape = mean$shape, dtype = tf$float64)
+   eps * k_exp(logvar * 0.5) + mean
+ }
> normal_loglik <- function(sample, mean, logvar, reduce_axis = 2) {
+   loglik <- k_constant(0.5, dtype = tf$float32) * 
+     (k_log(2 * k_constant(pi, dtype = tf$float32)) +
+        logvar +
+        k_exp(-logvar) * (sample - mean) ^ 2)
+   - k_sum(loglik, axis = reduce_axis)
+ }
> optimizer <- tf$optimizers$Adam(1e-4)
> num_examples_to_generate <- 64
> random_vector_for_generation <-
+   k_random_normal(shape = list(num_examples_to_generate, latent_dim),
+                   dtype = tf$float32)
> generate_random_clothes <- function(epoch) {
+   predictions <-
+     decoder(random_vector_for_generation) %>% tf$nn$sigmoid()
+   png(paste0("cvae_clothes_epoch_", epoch, ".png"))
+   par(mfcol = c(8, 8))
+   par(mar = c(0.5, 0.5, 0.5, 0.5),
+       xaxs = 'i',
+       yaxs = 'i')
+   for (i in 1:64) {
+     img <- predictions[i, , , 1]
+     img <- t(apply(img, 2, rev))
+     image(
+       1:28,
+       1:28,
+       img * 127.5 + 127.5,
+       col = gray((0:255) / 255),
+       xaxt = 'n',
+       yaxt = 'n'
+     )
+   }
+   dev.off()
+ }
> show_latent_space <- function(epoch) {
+   iter <- make_iterator_one_shot(test_dataset)
+   x <-  iterator_get_next(iter)
+   x_test_encoded <- encoder(x)[[1]]
+   x_test_encoded %>%
+     as.matrix() %>%
+     as.data.frame() %>%
+     mutate(class = class_names[fashion$test$y + 1]) %>%
+     ggplot(aes(x = V1, y = V2, colour = class)) + geom_point() +
+     theme(aspect.ratio = 1) +
+     theme(plot.margin = unit(c(0, 0, 0, 0), "null")) +
+     theme(panel.spacing = unit(c(0, 0, 0, 0), "null"))
+   
+   ggsave(
+     paste0("cvae_latentspace_epoch_", epoch, ".png"),
+     width = 10,
+     height = 10,
+     units = "cm"
+   )
+ }
> show_grid <- function(epoch) {
+   png(paste0("cvae_grid_epoch_", epoch, ".png"))
+   par(mar = c(0.5, 0.5, 0.5, 0.5),
+       xaxs = 'i',
+       yaxs = 'i')
+   n <- 16
+   img_size <- 28
+   
+   grid_x <- seq(-4, 4, length.out = n)
+   grid_y <- seq(-4, 4, length.out = n)
+   rows <- NULL
+   
+   for (i in 1:length(grid_x)) {
+     column <- NULL
+     for (j in 1:length(grid_y)) {
+       z_sample <- matrix(c(grid_x[i], grid_y[j]), ncol = 2)
+       column <-
+         rbind(column,
+               (decoder(z_sample) %>% tf$nn$sigmoid() %>% as.numeric()) %>% matrix(ncol = img_size))
+     }
+     rows <- cbind(rows, column)
+   }
+   rows %>% as.raster() %>% plot()
+   dev.off()
+ }
> num_epochs <- 50
> encoder <- encoder_model()
> decoder <- decoder_model()
> checkpoint_dir <- "./checkpoints_fashion_cvae"
> checkpoint_prefix <- file.path(checkpoint_dir, "ckpt")
> checkpoint <-
+   tf$train$Checkpoint(optimizer = optimizer,
+                       encoder = encoder,
+                       decoder = decoder)
> generate_random_clothes(0)
null device 
          1 
> show_latent_space(0)
> show_grid(0)
WARNING:tensorflow:Layer dense_1 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because its dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

null device 
          1 
> for (epoch in seq_len(num_epochs)) {
+   iter <- make_iterator_one_shot(train_dataset)
+   
+   total_loss <- 0
+   logpx_z_total <- 0
+   logpz_total <- 0
+   logqz_x_total <- 0
+   
+   until_out_of_range({
+     x <-  iterator_get_next(iter)
+     
+     with(tf$GradientTape(persistent = TRUE) %as% tape, {
+       
+       c(mean, logvar) %<-% encoder(x)
+       z <- reparameterize(mean, logvar)
+       preds <- decoder(z)
+       
+       crossentropy_loss <-
+         tf$nn$sigmoid_cross_entropy_with_logits(logits = preds, labels = x)
+       logpx_z <-
+         -k_sum(crossentropy_loss)
+       logpz <-
+         normal_loglik(z,
+                       k_constant(0, dtype = tf$float32),
+                       k_constant(0, dtype = tf$float32))
+       logqz_x <- normal_loglik(z, mean, logvar)
+       loss <- -k_mean(logpx_z + logpz - logqz_x)
+       
+     })
+     
+     total_loss <- total_loss + loss
+     logpx_z_total <- tf$reduce_mean(logpx_z) + logpx_z_total
+     logpz_total <- tf$reduce_mean(logpz) + logpz_total
+     logqz_x_total <- tf$reduce_mean(logqz_x) + logqz_x_total
+     
+     encoder_gradients <- tape$gradient(loss, encoder$variables)
+     decoder_gradients <- tape$gradient(loss, decoder$variables)
+     
+     optimizer$apply_gradients(purrr::transpose(list(
+       encoder_gradients, encoder$variables
+     )),
+     global_step = tf$train$get_or_create_global_step())
+     optimizer$apply_gradients(purrr::transpose(list(
+       decoder_gradients, decoder$variables
+     )),
+     global_step = tf$train$get_or_create_global_step())
+     
+   })
+   
+   checkpoint$save(file_prefix = checkpoint_prefix)
+   
+   cat(
+     glue(
+       "Losses (epoch): {epoch}:",
+       "  {(as.numeric(logpx_z_total)/batches_per_epoch) %>% round(2)} logpx_z_total,",
+       "  {(as.numeric(logpz_total)/batches_per_epoch) %>% round(2)} logpz_total,",
+       "  {(as.numeric(logqz_x_total)/batches_per_epoch) %>% round(2)} logqz_x_total,",
+       "  {(as.numeric(total_loss)/batches_per_epoch) %>% round(2)} total"
+     ),
+     "\n"
+   )
+   
+   if (epoch %% 10 == 0) {
+     generate_random_clothes(epoch)
+     show_latent_space(epoch)
+     show_grid(epoch)
+   }
+ }
Error: InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Mul]

Detailed traceback: 
  File "/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 490, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6143, in mul
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6803, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<s
```

**Comment by henry090** [comment]
I have added an example of loading GloVe vectors. It actually exists: https://github.com/rstudio/keras/blob/master/vignettes/examples/pretrained_word_embeddings.R
but the new one is very straightforward. Should it be added?

**Comment by skeydan** [comment]
Sorry if I was unclear... What I meant basically was just changing these lines (removing dtype): 

https://github.com/rstudio/keras/blob/506e4cfa7bd7b815ee265179b02a58a7a9fe0321/vignettes/examples/eager_cvae.R#L64

https://github.com/rstudio/keras/blob/506e4cfa7bd7b815ee265179b02a58a7a9fe0321/vignettes/examples/eager_cvae.R#L89

and then - but only if that worked so far - perhaps also remove the two dtype specifications here;

https://github.com/rstudio/keras/blob/506e4cfa7bd7b815ee265179b02a58a7a9fe0321/vignettes/examples/eager_cvae.R#L135

Could you still try this please, step by step - if already step  1 fails, no need to continue...

For the embeddings example, can you open a separate PR? I think we may even want to remove the old one, given this: https://github.com/rstudio/keras/blob/425db71364e74146a9988e9d573cebff6f18c306/vignettes/examples/pretrained_word_embeddings.R#L15

**Comment by henry090** [comment]
If I remove ```dtype``` from 89th line:
```
show_grid(0)
WARNING:tensorflow:Layer dense_1 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.
```
__And it works__ But if I change 135th line then it still throws that warning.


But with this:
```
self$dense <- layer_dense(units = 7 * 7 * 32, activation = "relu",dtype = 'float32')
```
No warnings/errors.

**Comment by skeydan** [comment]
This

> WARNING:tensorflow:Layer dense_1 is casting

really is just a warning so we could ignore it. However, it would be even better if we could make it go away by modifying the "other piece" in the incompatibility, referred to in

> is casting an input tensor from dtype float64 to

As this is thrown from `throw_grid`, the culprit should be some input generated there - probably, `z_sample` here:

https://github.com/rstudio/keras/blob/506e4cfa7bd7b815ee265179b02a58a7a9fe0321/vignettes/examples/eager_cvae.R#L217

You could try casting this one to `float32` before it is passed to the decoder.

**Comment by henry090** [comment]
I casted ‘’’z_sample’’’. Now, there are no warnings/errors

**Comment by skeydan** [comment]
Wonderful, looks very nice now! Merging :-)
Thanks again!

**Pull request merged**
