### PR TITLE
unet example

### PR DESCRIPTION
**Pull request by statist-bhfz**
unet example (https://github.com/rstudio/keras/issues/132)

unet architecture is based on original Python code from https://github.com/petrosgk/Kaggle-Carvana-Image-Masking-Challenge. 
It shows an example of creating custom architectures in R version of `keras` and working with images using `magick` package. 
`parallel` + `doParallel` + `foreach` allows to speed up the code.
You can download the data from https://www.kaggle.com/c/carvana-image-masking-challenge

### CODE REVIEW

**Comment by jjallaire** [comment]
When I run this on my Linux GPU box (TITAN Xp GPU, 32 GB of RAM, 8 cores) it hangs at "Epoch 1/30". At least once after this hang I got a message about being out of GPU memory.

I'm wondering if the parallel R stuff might be having a strange interaction with the fit_generator function? Maybe we should start with a version that doesn't use parallel R at all to see if that works as a baseline.

**Comment by statist-bhfz** [comment]
It works fine on Windows even with 1050ti, but I didn't check it on Linux
(I will do it soon).
This code assumes train masks in .png format, did you perform this
conversion? Is output of iter_next(train_iterator) looks like valid batch
arrays?

19.09.2017 15:05 пользователь "JJ Allaire" <notifications@github.com>
написал:

When I run this on my Linux GPU box (TITAN Xp GPU, 32 GB of RAM, 8 cores)
it hangs at "Epoch 1/30". At least once after this hang I got a message
about being out of GPU memory.

I'm wondering if the parallel R stuff might be having a strange interaction
with the fit_generator function? Maybe we should start with a version that
doesn't use parallel R at all to see if that works as a baseline.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rstudio/keras/pull/134#issuecomment-330518056>, or mute
the thread

**Comment by jjallaire** [comment]
On Tue, Sep 19, 2017 at 8:35 AM, Andrey Ogurtsov <notifications@github.com>
wrote:

> It works fine on Windows even with 1050ti, but I didn't check it on Linux
> (I will do it soon).
>


> This code assumes train masks in .png format, did you perform this
> conversion?


I didn't realize that there were files to download / convert as part of the
example. I would suggest that you do this as part of the script so others
don't run into the same issue. If there are large files that need to be
downloaded you can use the `get_file` function to do a cached download.

**Comment by statist-bhfz** [comment]
I have changed mask format to .gif, so any additional steps are not required anymore. Users should extract train images and mask into specified folders and start training (any files can not be shared according to Kaggle rules).

**Comment by jjallaire** [comment]
Could we automate the download using keras::get_file?

If not, could we provide some additional instructions on downloading and
extracting the files?

Thanks!

J.J.

**Comment by statist-bhfz** [comment]
@jjallaire I have no idea how we can simplify this process even further: the only legal way to use files from the competition is to accept competition rules and download files using links provided on competition page.
kag

**Comment by jjallaire** [comment]
Sorry about all the back and forth here. I just want to make sure that people can easily run the example. In terms of additional instructions, I'm thinking that while there is a test.zip and train.zip, etc. on Kaggle, the script assumes that they will be extracted into an "input" directory. I'm thinking something along the lines of:

```r
#' To run this example:
#' 
#'  1) Download the train.zip and train_masks.zip files from: 
#'     https://www.kaggle.com/c/carvana-image-masking-challenge/data
#' 
#'  2) Create an "input" directory and extract the zip files into it (after this there
#'     should be "train" and "train_masks" subdirectories within the "input" directory).
#'
```

I realize that this may seem pedantic but all of the other examples run out of the box so this is an expectation users will have. It's fine if we depend on data behind some authentication, we just need to be super-clear about it for people.

Thanks very much again for this example and sorry about all this back and forth, if you want me to add the suggested comment above I can just merge and then do so on master.

**Comment by statist-bhfz** [comment]
@ jjallaire Thanks, it will be great if you do so!

**Comment by jjallaire** [comment]
Okay, will do. I won't be back at my Linux GPU machine until Thursday but
I'll test and merge then.

**Comment by topepo** [comment]
> I'm wondering if the parallel R stuff might be having a strange interaction
with the fit_generator function? Maybe we should start with a version that
doesn't use parallel R at all to see if that works as a baseline.

When I was integrating some `keras` models into `caret`, I could not reliably get them to run in parallel. 

> When I run this on my Linux GPU box (TITAN Xp GPU, 32 GB of RAM, 8 cores) it hangs at "Epoch 1/30". At least once after this hang I got a message about being out of GPU memory.

The out of memory issue is likely to pop up since, when running with _M_ workers, you multiply the memory requirements by _M_.

**Comment by statist-bhfz** [comment]
@topepo This example in not about parallel model training, it's just about parallel image processing (reading, reshaping, augmentation). And the entire batch as a list of 2 arrays then passes to single model which is training in single GPU. 
Memory duplication happens only in RAM, but it is not very sufficient (this examle runs on 16GB, but 8 or even 4 should be enough).

**Comment by jjallaire** [comment]
Testing on my Linux GPU system now, for me the training hangs (going on 30 minutes now) at:

```
> model %>% fit_generator(
+     train_iterator,
+     steps_per_epoch = as.integer(length(train_index) / batch_size), 
+     epochs = epochs, 
+      .... [TRUNCATED] 
2017-09-21 09:18:38.062259: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-21 09:18:38.062299: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-21 09:18:38.062304: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-21 09:18:38.062321: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-21 09:18:38.062324: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-09-21 09:18:38.320257: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-21 09:18:38.320656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: TITAN Xp
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:01:00.0
Total memory: 11.90GiB
Free memory: 10.90GiB
2017-09-21 09:18:38.320700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-09-21 09:18:38.320728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-09-21 09:18:38.320756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0)
```

**Pull request closed without merging**
