### PR TITLE
Allow to pass additional args to ggplot2

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by jjallaire** [comment]
Looks like tests are failing because the .Rd link to ggplot isn't complete (you need `[ggplot2::ggplot()]`

**Comment by topepo** [comment]
I'm not sure that adding `...` adds much since people would want to modify the object by adding new geoms/scales/coords etc. These can be added to the object after the function is run. 

I think that a better approach would be to have a `broom::tidy` method that returns the data used for the plot. From that, people can do whatever they want.

**Comment by terrytangyuan** [comment]
Yes good point. I wasn't paying attention to the functionality but rather paying attention to the consistency of the documentation. Closing this since it's not very useful anyways. Thanks!

**Comment by terrytangyuan** [comment]
@topepo I believe this function already returns ggplot2 object so users can chain additional syntax on top of that. There's also keras_training_history object and as.data.frame that people can use that I think should be "tidy" enough.

**Comment by jjallaire** [comment]
Yes, if you call as.data.frame on the history object you get the data frame
used to create the plot

**Pull request closed without merging**
