### PR TITLE
Implement export_savedmodel S3 method

### PR DESCRIPTION
**Pull request by javierluraschi**
Reopening from https://github.com/rstudio/keras/pull/171 to add support for TensorFlow 1.4.

### CODE REVIEW

**Comment by jjallaire** [comment]
Looks like this PR subsumes #171 so we can close that. Correct?

This LGTM otherwise, any reason for me not to merge?

**Comment by jjallaire** [comment]
Oops, Travis failed, let em take a look

**Comment by jjallaire** [comment]
Maybe try merging master into this branch and see if the test passes?

**Comment by javierluraschi** [comment]
I was able to reproduce the failure locally... In my case the extracted `./keras/cifar.tar` did not have all 10 batches... I'm deleting `/keras` locally and retrying.

**Comment by javierluraschi** [comment]
@jjallaire failure got fixed locally after deleting CIFAR from my cache and re-runing tests. Seems like Travis is caching the CIFAR dataset as well... so we need to somehow delete the old cache in Travis?

**Comment by jjallaire** [comment]
I deleted the cache and restarted the build

**Pull request merged**
