### PR TITLE
expose renorm, renorm_clipping to layer_batch_normalization

### PR DESCRIPTION
**Pull request by ifrit98**
Have had a desire to use renorm from the R side with layer_batch_normalization, so simply exposed them in the function args and create_layer call.

### CODE REVIEW

**Comment by ifrit98** [comment]
Duplicate of #908

**Comment by dfalbel** [comment]
Could you also fix the docs?

**Comment by ifrit98** [comment]
Of course, updated the PR.  Also exposed the remaining arguments, updated the doc to reflect changes, and inserted a check for adjustment.

**Comment by dfalbel** [comment]
Thanks @ifrit98

**Comment by ifrit98** [comment]
@dfalbel, 'welcome!  Glad to.

**Pull request merged**
