### PR TITLE
plot method for training history

### PR DESCRIPTION
**Pull request by jjallaire**
Companion to https://github.com/rstudio/keras/commit/58ff8ade89c7a130567049a922cd869793fbdb06

```
> history
Trained on 60,000 samples (batch_size=128, epochs=10)
Final epoch (plot to see history):
val_loss: 0.08751
    loss: 0.08427
 val_acc: 0.9812
     acc: 0.9781

> str(history)
List of 2
 $ params :List of 6
  ..$ batch_size   : int 128
  ..$ samples      : int 60000
  ..$ verbose      : int 1
  ..$ do_validation: logi TRUE
  ..$ metrics      : chr [1:4] "loss" "acc" "val_loss" "val_acc"
  ..$ epochs       : int 10
 $ metrics:List of 4
  ..$ val_loss: num [1:10] 0.1228 0.1005 0.0995 0.0939 0.0888 ...
  ..$ loss    : num [1:10] 0.333 0.164 0.133 0.118 0.11 ...
  ..$ val_acc : num [1:10] 0.96 0.969 0.974 0.977 0.979 ...
  ..$ acc     : num [1:10] 0.898 0.952 0.961 0.967 0.97 ...
 - attr(*, "class")= chr "keras_training_history"

> plot(history)
```
plot_history

### CODE REVIEW

**Comment by jjallaire** [comment]
@terrytangyuan Let me know if you think this treatment for plot is okay. I don't include additional metadata like number of samples, number of validation samples, etc. b/c this is intended only as a diagnostic rather than something to be shared/published.

**Comment by terrytangyuan** [comment]
This looks fine for now if it's just for diagnostic info. Users should use those metadata themselves if they want to build more advanced plots.

**Comment by terrytangyuan** [comment]
BTW, I was looking into whether we should embed TensorBoard local server in RStudio like Shiny apps. Do you have a preferred/suggested way of doing it?

**Comment by jjallaire** [comment]
Yes, I'm working on that right now, branch is here:
https://github.com/rstudio/tensorflow/tree/feature/tensorboard-view

The TensorBoard UI isn't very responsive to smaller browser widths/heights
so I'll probably have it open in an external browser rather than within the
IDE.

**Comment by terrytangyuan** [comment]
Oh wow nice!!

**Pull request merged**
